import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "JessoDev",
  description: "Generated by create next app",
};


type Project = {
  id: number;
  name: string;
  desc: string;
  status: string;
  created_at: Date | null;
  updated_at: Date | null;
  techs_project: TechsProject[];
  project_images: ProjectImage[];
};

type ProjectImage = {
  id: number;
  project_id?: number;
  name: string;
  status: string;
  created_at: Date | null;
  updated_at: Date | null;
};

type TechsProject = {
  id: number;
  project_id: number;
  techs_id: number;
  created_at: Date | null;
  updated_at: Date | null;
  techs: ProjectImage;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetch("http://192.168.40.193:8000/api/public/index");
  const project : Project = await data.json();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
